# Permalinks
# 
permalink:           /:categories/:title

# Setup
title:               World of Oli
tagline:             'Programming stuff'
description:         'My development experiences, findings, and stuff others might find useful.'
url:                 http://ofalvai.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Olivér Falvai
  twitter:           https://twitter.com/ofalvai
  email:             ofalvai@gmail.com
  github:            https://github.com/ofalvai

# Custom vars
version:             1.0.0

# Build settings
markdown:            kramdown
gems:                [jekyll-paginate]
highlighter:         true