# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               World of Oli
tagline:             'Programming stuff'
description:         'TODO'
url:                 http://ofalvai.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Olivér Falvai
  url:               https://twitter.com/ofalvai
  email:             ofalvai@gmail.com

# Custom vars
version:             1.0.0

# Build settings
markdown: kramdown
highlighter: true
gems: [jekyll-paginate]